version: '3'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
    networks:
      - app-network

  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge